// Mirror of backend/src/config/permissions.js — keep in sync.
export const PERMISSION_CATALOG = [
  {
    group: 'Leads & CRM Pipeline',
    items: [
      { key: 'leads.view.own', label: 'View own assigned leads' },
      { key: 'leads.view.team', label: 'View team leads' },
      { key: 'leads.view.all', label: 'View all leads' },
      { key: 'leads.create', label: 'Create leads' },
      { key: 'leads.edit.own', label: 'Edit own leads' },
      { key: 'leads.edit.all', label: 'Edit any lead' },
      { key: 'leads.delete.own', label: 'Delete own leads' },
      { key: 'leads.delete.all', label: 'Delete any lead' },
      { key: 'leads.export', label: 'Export leads' },
      { key: 'leads.reassign', label: 'Reassign leads' },
      { key: 'leads.distribute', label: 'Lead distribution' },
      { key: 'leads.kanban', label: 'Sales Kanban board' },
    ],
  },
  {
    group: 'Offers & Bookings',
    items: [
      { key: 'offers.create', label: 'Create offers' },
      { key: 'offers.edit.own', label: 'Edit own offers' },
      { key: 'offers.edit.all', label: 'Edit any offer' },
      { key: 'offers.send', label: 'Send offers (email/SMS)' },
      { key: 'offers.revise', label: 'Revise offers' },
      { key: 'offers.delete', label: 'Delete offers' },
      { key: 'offers.templates', label: 'Manage offer templates' },
      { key: 'offers.view.all', label: 'View all offers' },
      { key: 'offers.images', label: 'Upload offer images' },
      { key: 'bookings.view', label: 'View bookings (lookup)' },
      { key: 'bookings.cancel', label: 'Cancel bookings' },
      { key: 'bookings.refund', label: 'Refund bookings' },
      { key: 'bookings.complete', label: 'Mark booking complete' },
      { key: 'payment.link.generate', label: 'Generate payment links' },
      { key: 'payment.process', label: 'Process payments' },
    ],
  },
  {
    group: 'Support Tickets',
    items: [
      { key: 'tickets.view.own', label: 'View own tickets' },
      { key: 'tickets.view.all', label: 'View all tickets' },
      { key: 'tickets.reply', label: 'Reply to tickets' },
      { key: 'tickets.create', label: 'Create tickets' },
      { key: 'tickets.edit', label: 'Edit tickets' },
      { key: 'tickets.delete', label: 'Delete tickets' },
      { key: 'tickets.assign', label: 'Assign tickets' },
      { key: 'tickets.export', label: 'Export tickets' },
    ],
  },
  {
    group: 'Campaigns & Marketing',
    items: [
      { key: 'campaigns.view', label: 'View campaigns' },
      { key: 'campaigns.create', label: 'Create campaigns' },
      { key: 'campaigns.edit', label: 'Edit campaigns' },
      { key: 'campaigns.delete', label: 'Delete campaigns' },
      { key: 'campaigns.form.generate', label: 'Generate lead forms' },
      { key: 'campaigns.form.embed', label: 'Embed/configure forms' },
      { key: 'marketing.assets', label: 'Manage marketing assets' },
    ],
  },
  {
    group: 'Analytics & Reporting',
    items: [
      { key: 'analytics.view.sales', label: 'Sales analytics' },
      { key: 'analytics.view.executive', label: 'Executive dashboard' },
      { key: 'analytics.view.rtm', label: 'RTM live monitor' },
      { key: 'analytics.export', label: 'Export reports' },
      { key: 'analytics.custom', label: 'Build custom reports' },
    ],
  },
  {
    group: 'User & Access Management',
    items: [
      { key: 'users.view', label: 'View users' },
      { key: 'users.create', label: 'Create users' },
      { key: 'users.edit', label: 'Edit users' },
      { key: 'users.delete', label: 'Delete users' },
      { key: 'users.suspend', label: 'Suspend/activate users' },
      { key: 'users.roles.assign', label: 'Assign roles' },
      { key: 'users.permissions.edit', label: 'Edit permissions' },
      { key: 'users.teams.manage', label: 'Manage teams' },
    ],
  },
  {
    group: 'HRM, Payroll & ESS',
    items: [
      { key: 'hrm.contracts.view', label: 'View contracts' },
      { key: 'hrm.contracts.edit', label: 'Edit contracts' },
      { key: 'hrm.schedules.view', label: 'View schedules' },
      { key: 'hrm.schedules.edit', label: 'Edit schedules' },
      { key: 'hrm.leaves.approve', label: 'Approve leave' },
      { key: 'hrm.govdocs.verify', label: 'Verify gov documents' },
      { key: 'hrm.training.manage', label: 'Manage training' },
      { key: 'hrm.talent.manage', label: 'Manage recruitment' },
      { key: 'hrm.partnerships.manage', label: 'Manage partnerships' },
      { key: 'payroll.runs.generate', label: 'Generate payroll runs' },
      { key: 'payroll.runs.approve', label: 'Approve payroll runs' },
      { key: 'payroll.runs.release', label: 'Release payroll' },
      { key: 'payroll.paymentmethods.approve', label: 'Approve payment methods' },
      { key: 'payroll.bank.verify', label: 'Verify bank accounts' },
      { key: 'payroll.loans.manage', label: 'Manage loans' },
      { key: 'payroll.alerts.view', label: 'View payroll alerts' },
      { key: 'ess.payslips.view', label: 'View own payslips' },
      { key: 'ess.schedule.view', label: 'View own schedule' },
      { key: 'ess.paymentmethods.manage', label: 'Manage own payment method' },
    ],
  },
  {
    group: 'System, Settings & Integrations',
    items: [
      { key: 'settings.view', label: 'View system settings' },
      { key: 'settings.edit', label: 'Edit system settings' },
      { key: 'settings.aux.configure', label: 'Configure AUX' },
      { key: 'settings.email.global', label: 'Configure global SMTP' },
      { key: 'gateway.manage', label: 'Manage payment gateways' },
      { key: 'gateway.bank.manage', label: 'Manage company bank' },
      { key: 'devtools.view', label: 'Use dev tools' },
      { key: 'audit.view', label: 'View audit logs' },
      { key: 'integrations.manage', label: 'Manage integrations' },
    ],
  },
  {
    group: 'Communication',
    items: [
      { key: 'email.send', label: 'Send internal email' },
      { key: 'email.view.inbox', label: 'View own inbox' },
      { key: 'email.view.all', label: 'View all mail' },
      { key: 'sms.send', label: 'Send SMS' },
      { key: 'avaya.call', label: 'Make Avaya calls' },
      { key: 'notifications.view', label: 'View notifications' },
    ],
  },
];

export const ALL_PERMISSION_KEYS = PERMISSION_CATALOG.flatMap(g => g.items.map(i => i.key));
